### ISSUE TITLE
featurecounts missing 3 required positional arguments

### ISSUE THREAD

**Issue by rstatistics** [SingleronBio/SCOPE-tools#22]
您好！我在运行下面这个命令的时候：
scope featureCounts \
    --input ./samplename/03.STAR/samplename_Aligned.sortedByCoord.out.bam \
    --annot ./references/Homo_sapiens/Ensembl/GRCh38/Homo_sapiens.GRCh38.99.gtf \
    --sample samplename \
    --outdir ./
报错如下：
Traceback (most recent call last):
  File "/home/admin/miniconda2/envs/scope/bin/scope", line 10, in <module>
    sys.exit(cli())
  File "/home/admin/miniconda2/envs/scope/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/admin/miniconda2/envs/scope/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/admin/miniconda2/envs/scope/lib/python3.7/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/admin/miniconda2/envs/scope/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/admin/miniconda2/envs/scope/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/admin/miniconda2/envs/scope/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
TypeError: featurecounts_pipe() missing 3 required positional arguments: 'format', 'nthreads', and 'type'
麻烦您帮忙解决一下，谢谢~

**Comment by luyang93** [comment]
fixed in #24

**Comment by rstatistics** [comment]
ok, thanks!
